### ISSUE TITLE
Source Code of the Paper

### ISSUE THREAD

**Issue by BangW2001** [whyisyoung/JigsawPuzzle#2]
I recently read your paper "Jigsaw Puzzle: Selective Backdoor Attack to Subvert Malware Classifiers" and I think it is very interesting. But unfortunately, I have some problem when I try to implement your algorithm. Could you please public the source code of your algorithm?

**Comment by whyisyoung** [comment]
Sorry for the delay. The website is updated. You can ask for code access here: https://whyisyoung.github.io/JigsawPuzzle/
